export const FEATURED_PROMOS = [
  {
    id: "casino-hire",
    tag: "모집 공고",
    title: "아시아 최대 카지노\n딜러 채용 공고",
    desc: "월 500만원 이상 · 숙소 제공 · 항공 지원",
    meta: "카지노코리아  2025.04.09",
    cta: "자세히 보기",
    href: "/boards/jobs/fixed",
    tone: "city",
  },
  {
    id: "spring",
    tag: "이벤트",
    title: "POKA x 파라다이스\n봄맞이 특별 이벤트!",
    desc: "SPRING EVENT",
    meta: "파라다이스 카지노  추천인 해도 50만원 지급!",
    cta: "자세히 보기",
    href: "/boards/schedule",
    tone: "spring",
  },
  {
    id: "dealer-fit",
    tag: "홍보",
    title: "딜러 전용 의류 브랜드\n신규 런칭!",
    desc: "DEALER FIT",
    meta: "프로페셔널 더 빛나는 당신을 위해",
    cta: "자세히 보기",
    href: "/boards/official",
    tone: "fit",
  },
  {
    id: "gangnam",
    tag: "구인",
    title: "강남 대형 카지노\n딜러 모집합니다",
    desc: "초보 가능 · 경력 우대 · 숙식 제공",
    meta: "VIP 카지노  2025.04.07",
    cta: "자세히 보기",
    href: "/boards/jobs/apply",
    tone: "hotel",
  },
  {
    id: "english",
    tag: "정보",
    title: "딜러에게 꼭 필요한\n필수 영어 표현 모음",
    desc: "현장 실무에 바로 쓰는 영어",
    meta: "POKA 매거진  2025.04.06",
    cta: "자세히 보기",
    href: "/info/tips",
    tone: "paper",
  },
  {
    id: "welcome",
    tag: "이벤트",
    title: "신규 가입 이벤트\n포인트 10,000P 지급!",
    desc: "WELCOME 10,000P",
    meta: "지금 가입하면 바로 지급됩니다.",
    cta: "자세히 보기",
    href: "/about",
    tone: "welcome",
  },
] as const;
