export const PWA_NAME = "POKA - 홀덤·딜러 커뮤니티";
export const PWA_SHORT_NAME = "POKA";
export const PWA_START_URL = "/";
export const PWA_DISPLAY = "standalone" as const;
export const PWA_THEME_COLOR = "#07150f";
export const PWA_BACKGROUND_COLOR = "#07150f";
export const PWA_ICON_192 = "/icons/poka-192.png";
export const PWA_ICON_512 = "/icons/poka-512.png";
export const PWA_APPLE_ICON = "/icons/poka-180.png";
