ALTER TYPE "BoardType" ADD VALUE IF NOT EXISTS 'NOTICE';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pointsEarnedDate" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "pointsEarnedToday" INTEGER NOT NULL DEFAULT 0;
